name: Training
description: Trains a model on processed data and outputs training results.
inputs:
  - {name: processed_data, type: Dataset}
outputs:
  - {name: training_output, type: Dataset}
implementation:
  container:
    image: model-training-service:latest
    command: [
      "python",
      "/app/train.py"
    ]
    args: [
      "--input_path", {inputPath: processed_data},
      "--output_path", "/output/train_output.json"
    ]
    fileOutputs:
      training_output: "/output/train_output.json"
