apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-agent
  namespace: kubeflow
  labels:
    app: proxy-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-agent
  template:
    metadata:
      labels:
        app: proxy-agent
    spec:
      containers:
      - name: proxy-agent
        image: gcr.io/kubeflow-images-public/proxy-agent:<version>
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_MAP_NAME
          value: "inverse-proxy-config"
        command:
        - "/bin/bash"
        - "-c"
        - "/opt/proxy/attempt-register-vm-on-proxy.sh"
