apiVersion: v1
kind: Service
metadata:
  name: preprocessing-service
spec:
  type: ClusterIP
  selector:
    app: preprocessing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
