apiVersion: v1
kind: Service
metadata:
  name: model-training-service
spec:
  type: ClusterIP
  selector:
    app: model-training-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # This port is not used in Option B but kept for consistency
